# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-10 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blero_grid', '0003_auto_20181208_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='blerogrid',
            name='content_edited',
            field=models.BooleanField(default=False),
        ),
    ]
