# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormInputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_name', models.CharField(blank=True, max_length=100, null=True)),
                ('input_type', models.CharField(blank=True, choices=[('text', 'TextBox'), ('date', 'Date Field'), ('checkbox', 'Checkbox')], max_length=250, null=True)),
                ('input_value', models.CharField(blank=True, max_length=250, null=True, verbose_name='Default Value')),
            ],
            options={
                'verbose_name_plural': 'New Fields',
                'verbose_name': 'New Field',
            },
        ),
        migrations.CreateModel(
            name='FormPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='form_addon_formplugin', serialize=False, to='cms.CMSPlugin')),
                ('load_form', models.CharField(blank=True, choices=[('new', 'New Form'), ('load', 'Load Form')], default='new', max_length=250, null=True)),
                ('model_name', models.CharField(blank=True, max_length=250, null=True)),
                ('form_name', models.CharField(blank=True, max_length=250, null=True)),
                ('button_name', models.CharField(blank=True, max_length=250, null=True)),
                ('ajax_function', models.CharField(blank=True, max_length=250, null=True)),
                ('py_function', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Addon Forms New',
                'verbose_name': 'Addon Form New',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ModelsInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_name', models.CharField(blank=True, max_length=100, null=True)),
                ('input_type', models.CharField(blank=True, choices=[('text', 'TextBox'), ('date', 'Date Field'), ('checkbox', 'Checkbox')], max_length=250, null=True)),
                ('input_value', models.CharField(blank=True, max_length=250, null=True, verbose_name='Default Value')),
            ],
        ),
        migrations.CreateModel(
            name='StoreModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajax_function', models.CharField(blank=True, max_length=250, null=True)),
                ('py_function', models.CharField(blank=True, max_length=250, null=True)),
                ('regressors', models.CharField(blank=True, max_length=250, null=True)),
                ('target', models.CharField(blank=True, max_length=250, null=True)),
                ('model_name', models.CharField(blank=True, max_length=250, null=True)),
                ('form_name', models.CharField(blank=True, max_length=250, null=True)),
                ('model_comments', models.CharField(blank=True, max_length=250, null=True)),
                ('button_name', models.CharField(blank=True, max_length=250, null=True)),
                ('from_date', models.CharField(blank=True, max_length=250, null=True)),
                ('to_date', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='modelsinput',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_addon.StoreModels'),
        ),
        migrations.AddField(
            model_name='forminputs',
            name='id_fr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_plugin', to='form_addon.FormPlugin'),
        ),
    ]
