# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_addon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSavePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resized', models.BooleanField(default=False)),
                ('width', models.CharField(max_length=50, null=True)),
                ('height', models.CharField(max_length=50, null=True)),
                ('top', models.CharField(max_length=50, null=True)),
                ('left', models.CharField(max_length=50, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_addon.FormPlugin')),
            ],
        ),
    ]
