# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_addon', '0006_auto_20180927_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formplugin',
            name='load_form',
        ),
        migrations.RemoveField(
            model_name='formplugin',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='modelsinput',
            name='model',
        ),
        migrations.DeleteModel(
            name='StoreModels',
        ),
    ]
