# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-23 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_addon', '0009_formbtnpluginposition_labelpluginposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbtnpluginposition',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btn_position', to='form_addon.FormInputs'),
        ),
        migrations.AlterField(
            model_name='inputpluginposition',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inp_position', to='form_addon.FormInputs'),
        ),
        migrations.AlterField(
            model_name='labelpluginposition',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label_position', to='form_addon.FormInputs'),
        ),
    ]
