# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blero_grid', '0004_blerogrid_content_edited'),
        ('form_addon', '0011_auto_20181123_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='BleroGridForm',
            fields=[
                ('blerogrid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blero_grid.BleroGrid')),
                ('parent_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_addon.FormPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('blero_grid.blerogrid',),
        ),
    ]
