# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-15 08:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.datetime(2018, 12, 15, 8, 31, 47, 143864))),
                ('date_completed', models.DateField()),
                ('is_complete', models.BooleanField(default=False)),
                ('task_title', models.CharField(default='New Task', max_length=250)),
                ('task_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskHolder',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='task_tracker_taskholder', serialize=False, to='cms.CMSPlugin')),
                ('holder_label', models.CharField(max_length=200)),
                ('since_date', models.DateField(default=datetime.datetime(2017, 12, 15, 8, 31, 47, 143036))),
                ('only_completed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='task_tracker.TaskHolder'),
        ),
    ]
