# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-15 08:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 12, 15, 8, 34, 1, 130749)),
        ),
        migrations.AlterField(
            model_name='taskholder',
            name='since_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 15, 8, 34, 1, 129850)),
        ),
    ]
