# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-15 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import task_tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0002_auto_20181215_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='taskholder',
            name='since_date',
            field=models.DateField(default=task_tracker.models.one_year_before),
        ),
    ]
