# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-15 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0003_auto_20181215_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='date_completed',
            field=models.DateField(null=True),
        ),
    ]
