# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 20:22
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('dashboards_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dash_docs_content', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentation_content', slotname='documentation_content', to='cms.Placeholder')),
                ('dashboard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards_app.Dashboard')),
                ('sidebar_content', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentation_sidebar_content', slotname='documentation_sidebar_content', to='cms.Placeholder')),
            ],
        ),
    ]
