# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_docs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(blank=True, max_length=250, null=True)),
                ('is_documented', models.BooleanField()),
                ('documented_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
