# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_docs_app', '0002_documentedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentedmodel',
            name='is_documented',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
