# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_docs_app', '0003_auto_20180923_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentedmodel',
            name='is_documented',
        ),
    ]
